### ISSUE TITLE
bcm git merge

### ISSUE THREAD

**Issue by AndrewIammatteo** [BitcoinCacheMachine/BitcoinCacheMachine#24]
Enable signing of the merge commit with bcm

**Comment by AndrewIammatteo** [comment]
This should also include the feature to verify signatures on merge

**Comment by AndrewIammatteo** [comment]
Merge signs and verifies signatures but trezor does not request that you confirm. This may take a while. I filed an issue with romanz/trezor. Awaiting response.

**Comment by farscapian** [comment]
All issues are now going to be tracked directly in the codebase using # TODO stanzas.
