### ISSUE TITLE
Ensure setup.sh does not interfere with ~/.bashrc

### ISSUE THREAD

**Issue by farscapian** [BitcoinCacheMachine/BitcoinCacheMachine#9]
It has been suggested that BCM intereferes with ~/.bashrc.  Do some testing to ensure that there are no adverse side-effects.

**Comment by AndrewIammatteo** [comment]
Tested in 2 ways:
1. Left a comment in .bashrc. Ran ./setup.sh BCM concatenated to the end of the file. Only possible improvement is to add a blank line before writing.
2. Deleted .bashrc and ran ./setup.sh. It created the .bashrc file and wrote in the commands. It did give an error "grep: /home/ai/.bashrc: No such file or directory" in the comments as the setup proceded. This was after the comment "Setting BCM_GIT_DIR environment variable in current shell to '/home/ai/git/github/bcm'" and before "Writing commands to '/home/ai/.bashrc' to enable the BCM CLI."

**Comment by farscapian** [comment]
All issues are now going to be tracked directly in the codebase using # TODO stanzas.
